name: Build Docker Container

on:
    workflow_run:
        workflows: ["Add Useless Comment"]
        types: [completed]

jobs:
    build-docker-container:
        name: Build Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: |
                docker build -t myapp:test .
